// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjZvl7Lxmj-Kk76KY0YtHN5UWCHt5Y4xQ',
    appId: '1:400541898199:web:90ec93358abd148127a792',
    messagingSenderId: '400541898199',
    projectId: 'jornada-gamer-d28a3',
    authDomain: 'jornada-gamer-d28a3.firebaseapp.com',
    storageBucket: 'jornada-gamer-d28a3.firebasestorage.app',
    measurementId: 'G-MR6NEGDRY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC11xKaWhtaQJfpp5dCrkDpOC4Clxbif8Q',
    appId: '1:400541898199:android:d2725ec5e51fef2827a792',
    messagingSenderId: '400541898199',
    projectId: 'jornada-gamer-d28a3',
    storageBucket: 'jornada-gamer-d28a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6qWfB_DgQA-MlmODeeiFuNNLF98zsHGo',
    appId: '1:400541898199:ios:e72aa7448eda50e027a792',
    messagingSenderId: '400541898199',
    projectId: 'jornada-gamer-d28a3',
    storageBucket: 'jornada-gamer-d28a3.firebasestorage.app',
    iosBundleId: 'com.example.jornadaGamer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6qWfB_DgQA-MlmODeeiFuNNLF98zsHGo',
    appId: '1:400541898199:ios:e72aa7448eda50e027a792',
    messagingSenderId: '400541898199',
    projectId: 'jornada-gamer-d28a3',
    storageBucket: 'jornada-gamer-d28a3.firebasestorage.app',
    iosBundleId: 'com.example.jornadaGamer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjZvl7Lxmj-Kk76KY0YtHN5UWCHt5Y4xQ',
    appId: '1:400541898199:web:5c4749be2276886027a792',
    messagingSenderId: '400541898199',
    projectId: 'jornada-gamer-d28a3',
    authDomain: 'jornada-gamer-d28a3.firebaseapp.com',
    storageBucket: 'jornada-gamer-d28a3.firebasestorage.app',
    measurementId: 'G-WG1WZB21LD',
  );
}
